/* app.js - Ритм v17.0 */
const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => document.querySelectorAll(sel);
const animate = (el, target, duration = 700) => { if (!el) return; const start = parseInt(el.textContent) || 0; const t0 = performance.now(); const step = (t) => { const p = Math.min((t - t0) / duration, 1); const ease = 1 - Math.pow(1 - p, 3); el.textContent = Math.round(start + (target - start) * ease); if (p < 1) requestAnimationFrame(step); }; requestAnimationFrame(step); };

// Theme
const themeToggle = $('#theme-toggle');
if (themeToggle) { const s = localStorage.getItem('fb_theme') || 'light'; document.documentElement.setAttribute('data-theme', s); themeToggle.textContent = s === 'dark' ? '☀️' : '🌙'; themeToggle.addEventListener('click', () => { const n = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark'; document.documentElement.setAttribute('data-theme', n); localStorage.setItem('fb_theme', n); themeToggle.textContent = n === 'dark' ? '☀️' : '🌙'; }); }

// Import
const importBtn = $('#import-btn'), importInput = $('#import-input');
if (importBtn && importInput) { importBtn.addEventListener('click', () => importInput.click()); importInput.addEventListener('change', (e) => { const file = e.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = (ev) => { try { const d = JSON.parse(ev.target.result); if (d.app === "Ритм" || d.app === "FocusBoard") { if(d.tasks) localStorage.setItem('fb_tasks', JSON.stringify(d.tasks)); if(d.calendarTasks) localStorage.setItem('fb_calTasks', JSON.stringify(d.calendarTasks)); if(d.profile) localStorage.setItem('fb_profile', JSON.stringify(d.profile)); alert('✅ Восстановлено!'); location.reload(); } else alert('❌ Неверный формат'); } catch (err) { alert('❌ Ошибка чтения'); } }; reader.readAsText(file); e.target.value = ''; }); }

// Safe Dates
const getLocalDateStr = (date = new Date()) => { const y = date.getFullYear(), m = String(date.getMonth()+1).padStart(2,'0'), d = String(date.getDate()).padStart(2,'0'); return `${y}-${m}-${d}`; };

// Auto Distribute
function autoDistributeTask(task, profile, calTasks) { const today = new Date(); today.setHours(0,0,0,0); const todayStr = getLocalDateStr(today); const dp = task.deadline.split('-'); const deadline = new Date(dp[0], dp[1]-1, dp[2]); deadline.setHours(23,59,59,999); if (deadline < today) return []; const diff = Math.abs(deadline - today); const daysUntil = Math.ceil(diff / 86400000) + 1; let remaining = task.totalH; const assignments = [], maxFocus = profile.maxFocus || 4, buffer = 0.5, vl = new Map(); calTasks.forEach(t => { if (t && t.date >= todayStr) vl.set(t.date, (vl.get(t.date)||0) + t.hours); }); for (let i = 0; i < daysUntil && remaining > 0.05; i++) { const d = new Date(today); d.setDate(d.getDate()+i); const ds = getLocalDateStr(d); const used = vl.get(ds) || 0; let avail = Math.max(0, maxFocus - used - buffer); if (avail <= 0) continue; let fd = 0; for (let j = i; j < daysUntil; j++) { const f = new Date(today); f.setDate(f.getDate()+j); if ((maxFocus - (vl.get(getLocalDateStr(f))||0) - buffer) > 0) fd++; } if (fd === 0) break; let ideal = remaining / fd, assign = Math.min(avail, Math.round(ideal * 2) / 2); if (Math.random() > 0.6 && assign + 0.25 <= avail) assign += 0.25; else if (Math.random() > 0.6 && assign - 0.25 >= 0.5) assign -= 0.25; assignments.push({ id: task.id, title: task.title, date: ds, hours: assign }); remaining -= assign; vl.set(ds, used + assign); } if (remaining > 0.05 && assignments.length > 0) assignments[assignments.length-1].hours += remaining; return assignments; }

function fireConfetti() { const cv=document.createElement('canvas'); cv.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:9999;'; cv.width=innerWidth; cv.height=innerHeight; document.body.appendChild(cv); const ctx=cv.getContext('2d'), p=[]; for(let i=0;i<100;i++) p.push({x:cv.width/2,y:cv.height/2,vx:(Math.random()-.5)*16,vy:(Math.random()-.5)*16-5,c:['#3b82f6','#ef4444','#10b981','#f59e0b'][Math.random()*4|0],l:90}); (function loop(){ ctx.clearRect(0,0,cv.width,cv.height); let a=false; p.forEach(q=>{if(q.l>0){a=true;q.x+=q.vx;q.y+=q.vy;q.vy+=0.5;q.l--;ctx.fillStyle=q.c;ctx.fillRect(q.x,q.y,7,7);}}); a?requestAnimationFrame(loop):cv.remove(); })(); }

// === 1️⃣ ГЛАВНАЯ ===
if ($('#hero-title')) { const t=$('#hero-title'), txt=t.textContent; t.textContent=''; let i=0; (function type(){if(i<txt.length){t.textContent+=txt.charAt(i++);setTimeout(type,35+Math.random()*25);}})(); const c=$('#hero-canvas'); if(c){const ctx=c.getContext('2d');let w=c.width=c.offsetWidth,h=c.height=c.offsetHeight;const pts=Array.from({length:40},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*1.2,vy:(Math.random()-.5)*1.2,s:Math.random()*2.5+1,a:Math.random()*.35+.1}));let mx=w/2,my=h/2;window.addEventListener('resize',()=>{w=c.width=c.offsetWidth;h=c.height=c.offsetHeight;});document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;});document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();pts.forEach(p=>{p.vx=(Math.random()-0.5)*10;p.vy=(Math.random()-0.5)*10;});}});(function loop(){ctx.clearRect(0,0,w,h);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=0.96;p.vy*=0.96;if(Math.abs(mx-p.x)<100)p.vx-=(mx-p.x)*0.002;if(Math.abs(my-p.y)<100)p.vy-=(my-p.y)*0.002;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.s,0,Math.PI*2);const isDark=document.documentElement.getAttribute('data-theme')==='dark';ctx.fillStyle=isDark?`rgba(96,165,250,${p.a})`:`rgba(59,130,246,${p.a})`;ctx.fill();});requestAnimationFrame(loop);})();}}

// === 2️⃣ МЕТОД ===
if ($('#rings-wrapper')) { const obs = new IntersectionObserver(e => { e.forEach(x => { if(x.isIntersecting) { animate($('#val-low'),45,1000); animate($('#val-med'),60,1000); animate($('#val-high'),85,1000); $('#ring-low').style.strokeDashoffset=314-(314*.45); $('#ring-med').style.strokeDashoffset=314-(314*.6); $('#ring-high').style.strokeDashoffset=314-(314*.85); obs.unobserve(x.target); } }); }, {threshold:.3}); obs.observe($('#rings-wrapper')); $$('.card-3d').forEach(el => { el.addEventListener('mousemove', e => { const r=el.getBoundingClientRect(); const x=(e.clientX-r.left)/r.width-.5, y=(e.clientY-r.top)/r.height-.5; el.style.transform=`perspective(800px) rotateY(${x*12}deg) rotateX(${-y*12}deg)`; }); el.addEventListener('mouseleave', () => el.style.transform='perspective(800px) rotateY(0) rotateX(0)'); }); }

// === 3️⃣ ДОСКА ===
if ($('#board')) {
  const datePlus = (days) => { const d = new Date(); d.setDate(d.getDate() + days); return getLocalDateStr(d); };
  let tasks = JSON.parse(localStorage.getItem('fb_tasks')) || [{id:'1',title:'Изучить DOM API',energy:'high',totalH:8,deadline:datePlus(14)},{id:'2',title:'Проверить почту',energy:'low',totalH:1,deadline:datePlus(7)}];
  let calTasks = JSON.parse(localStorage.getItem('fb_calTasks')) || [];
  const profile = JSON.parse(localStorage.getItem('fb_profile')) || { maxFocus: 4 };
  const saveTasks = () => localStorage.setItem('fb_tasks', JSON.stringify(tasks));
  const saveCal = () => localStorage.setItem('fb_calTasks', JSON.stringify(calTasks));
  const updateCounts = () => { ['low','med','high','done'].forEach(c => { const n=tasks.filter(t=>t.col===c||(!t.col&&t.energy===c&&c!=='done')).length; const el=$(`#count-${c}`); if(!el)return; el.textContent=n; el.classList.remove('bump'); void el.offsetWidth; el.classList.add('bump'); }); };
  
  const renderBoard = (sq = '') => {
    ['low','med','high','done'].forEach(c => { 
      const l=$(`#list-${c}`); if(!l)return; l.innerHTML=''; 
      tasks.forEach(t => { 
        const tr=t.col||(c!=='done'&&t.energy); 
        if(tr===c) {
          if (sq && !t.title.toLowerCase().includes(sq.toLowerCase())) return;
          const el=document.createElement('div'); 
          el.className=`task-card ${c==='done'?'done':''}`; 
          el.draggable=true; el.dataset.id=t.id; el.dataset.energy=t.energy; 
          let planHTML = '';
          if (t.plan && t.plan.length > 0) {
            const doneSteps = t.plan.filter(p => p.done).length; const pct = (doneSteps / t.plan.length) * 100;
            planHTML = `<div class="task-plan-bar"><div class="task-plan-fill ${pct === 100 ? 'complete' : ''}" style="width: ${pct}%"></div></div>`;
          }
          el.innerHTML=`<button class="task-open-btn">👁</button><h4>${t.title}</h4><div class="meta"><span>⏱️ ${t.totalH}ч | 📅 ${t.deadline}</span></div><button class="delete-btn">&times;</button>${planHTML}`; 
          l.appendChild(el); 
        } 
      }); 
    }); updateCounts();
  };

  const searchInput = $('#task-search');
  if (searchInput) searchInput.addEventListener('input', (e) => renderBoard(e.target.value));
  $$('.column').forEach(col => { col.addEventListener('dragover', e => { e.preventDefault(); col.classList.add('drag-over'); }); col.addEventListener('dragleave', () => col.classList.remove('drag-over')); col.addEventListener('drop', e => { e.preventDefault(); col.classList.remove('drag-over'); const id=e.dataTransfer.getData('text/plain'); const t=tasks.find(x=>x.id===id); if(t){t.col=col.dataset.col; if(col.dataset.col==='done'){calTasks=calTasks.filter(ct=>ct.id!==id);t.completedAt=getLocalDateStr(new Date());fireConfetti();}saveTasks();saveCal();renderBoard(searchInput?.value);} }); });
  document.addEventListener('dragstart', e => { if(e.target.classList.contains('task-card')){e.dataTransfer.setData('text/plain',e.target.dataset.id);e.target.classList.add('dragging');} });
  document.addEventListener('dragend', e => e.target.classList.remove('dragging'));
  document.addEventListener('click', e => { 
    if(e.target.classList.contains('delete-btn')){tasks=tasks.filter(t=>t.id!==e.target.parentElement.dataset.id);saveTasks();renderBoard(searchInput?.value); return;} 
    if(e.target.classList.contains('task-open-btn')) {
      const card = e.target.closest('.task-card'); const taskId = card.dataset.id; const task = tasks.find(t => t.id === taskId); if (!task) return;
      const detailModal = $('#task-detail-modal'); $('#detail-title').textContent = task.title;
      const eE = {low:'🔋',med:'⚡',high:'🔥'}; $('#detail-meta').textContent = `⏱️ ${task.totalH}ч | 📅 ${task.deadline} | ${eE[task.energy]} ${task.energy}`;
      const planList = $('#detail-plan-list'), planSection = $('#detail-plan-section');
      if (task.plan && task.plan.length > 0) { planSection.style.display='block'; planList.innerHTML='';
        task.plan.forEach((step, idx) => { const li=document.createElement('li'); li.className=`plan-check-item ${step.done?'checked':''}`; li.innerHTML=`<div class="plan-checkbox">${step.done?'✓':''}</div><div class="plan-step-text">${step.text}</div>`; li.addEventListener('click',()=>{task.plan[idx].done=!task.plan[idx].done;saveTasks();li.classList.toggle('checked');li.querySelector('.plan-checkbox').textContent=task.plan[idx].done?'✓':'';const cb=document.querySelector(`.task-card[data-id="${task.id}"]`);if(cb){const ds=task.plan.filter(p=>p.done).length;const pc=(ds/task.plan.length)*100;const f=cb.querySelector('.task-plan-fill');if(f){f.style.width=`${pc}%`;f.classList.toggle('complete',pc===100);}}}); planList.appendChild(li); });
      } else planSection.style.display='none';
      detailModal.classList.add('open');
    }
  });

  const modal = $('#add-task-modal'), openBtn = $('#open-task-btn');
  if(openBtn && modal) { openBtn.addEventListener('click', () => modal.classList.add('open')); modal.querySelector('.modal-close').addEventListener('click', () => modal.classList.remove('open')); modal.addEventListener('click', e => { if(e.target===modal) modal.classList.remove('open'); }); $('#manual-task-form').addEventListener('submit', e => { e.preventDefault(); const nt={id:Date.now().toString(),title:$('#m-title').value,energy:$('#m-energy').value,totalH:parseInt($('#m-hours').value),deadline:$('#m-deadline').value,col:$('#m-energy').value,plan:[]}; tasks.push(nt); const as=autoDistributeTask(nt,profile,calTasks); calTasks.push(...as); saveTasks();saveCal();renderBoard(searchInput?.value);fireConfetti(); modal.classList.remove('open');$('#manual-task-form').reset();alert(`✅ Задача создана на ${as.length} дней.`); }); }

  const planModal = $('#add-plan-modal'), planBtn = $('#open-plan-btn');
  const addPlanStep = (placeholder = '') => { const container=$('#plan-steps-container'); const div=document.createElement('div'); div.className='form-group plan-step-group'; div.style.marginBottom='0.8rem'; div.innerHTML=`<div style="display:flex;gap:8px;align-items:center;"><input type="text" class="form-input plan-step-input" placeholder="${placeholder||'Опиши шаг...'}" required style="flex:1;"><button type="button" class="icon-btn small remove-step-btn" style="background:rgba(239,68,68,0.1);color:var(--danger);flex-shrink:0;border:1px solid rgba(239,68,68,0.2);">✕</button></div>`; container.appendChild(div); };
  if(planBtn && planModal) { planBtn.addEventListener('click',()=>{planModal.classList.add('open');$('#plan-steps-container').innerHTML='';addPlanStep('🚀 Шаг старта');addPlanStep('🧱 Главный барьер');addPlanStep('⚡ Микро-действие');}); planModal.querySelector('.modal-close').addEventListener('click',()=>planModal.classList.remove('open')); planModal.addEventListener('click',e=>{if(e.target===planModal)planModal.classList.remove('open');}); $('#add-plan-step-btn').addEventListener('click',()=>addPlanStep()); $('#plan-steps-container').addEventListener('click',e=>{if(e.target.classList.contains('remove-step-btn'))e.target.closest('.plan-step-group').remove();}); $('#plan-task-form').addEventListener('submit',e=>{e.preventDefault();const planSteps=[...$$('.plan-step-input')].map(i=>({text:i.value,done:false}));if(planSteps.length===0){alert('Добавь шаг!');return;}const nt={id:Date.now().toString(),title:$('#p-title').value,energy:$('#p-energy').value,totalH:parseInt($('#p-hours').value),deadline:$('#p-deadline').value,col:$('#p-energy').value,plan:planSteps};tasks.push(nt);const as=autoDistributeTask(nt,profile,calTasks);calTasks.push(...as);saveTasks();saveCal();renderBoard(searchInput?.value);fireConfetti();planModal.classList.remove('open');$('#plan-task-form').reset();alert(`✅ Задача с планом создана на ${as.length} дней.`);}); }
  const detailModal=$('#task-detail-modal'); if(detailModal){detailModal.querySelector('.modal-close').addEventListener('click',()=>detailModal.classList.remove('open'));detailModal.addEventListener('click',e=>{if(e.target===detailModal)detailModal.classList.remove('open');});}
  document.addEventListener('keydown',e=>{if(document.activeElement.tagName==='INPUT'||document.activeElement.tagName==='SELECT')return;if(e.key==='Escape'){modal?.classList.remove('open');planModal?.classList.remove('open');detailModal?.classList.remove('open');}});
  renderBoard();
  const isMob=window.matchMedia('(max-width:768px)').matches||'ontouchstart'in window; if(isMob){let sel=null;document.addEventListener('click',e=>{const task=e.target.closest('.task-card'),col=e.target.closest('.column');if(task&&!col){e.stopPropagation();document.querySelectorAll('.task-card').forEach(c=>c.classList.remove('mobile-selected'));task.classList.add('mobile-selected');sel=task;}else if(col&&sel){const tid=sel.dataset.id,tc=col.dataset.col,t=tasks.find(x=>x.id===tid);if(t){t.col=tc;if(tc==='done'){calTasks=calTasks.filter(ct=>ct.id!==tid);t.completedAt=getLocalDateStr(new Date());saveCal();fireConfetti();}saveTasks();sel.classList.remove('mobile-selected');sel=null;renderBoard(searchInput?.value);}}else if(!task&&!col){document.querySelectorAll('.task-card').forEach(c=>c.classList.remove('mobile-selected'));sel=null;}});}
}

// === 4️⃣ КАЛЕНДАРЬ ===
if ($('#calendar-grid')) { 
  const dp={sleep:'23:00',wake:'07:00',workS:'09:00',workE:'15:00',meal1:'08:00',meal2:'13:00',meal3:'19:00',breakEvery:90,maxFocus:4}; let profile=JSON.parse(localStorage.getItem('fb_profile')||'null')||{...dp}; profile={...dp,...profile}; 
  let calTasks=Array.isArray(JSON.parse(localStorage.getItem('fb_calTasks')||'null'))?JSON.parse(localStorage.getItem('fb_calTasks')):[]; 
  const todayStr=getLocalDateStr(new Date()); let currentMonth=new Date(),currentTimeline=[],selDate=null,timelineCounter=0; const area=$('#calendar-area'); 
  const minLim=new Date(new Date().getFullYear(),new Date().getMonth(),1),maxLim=new Date(new Date().getFullYear(),new Date().getMonth()+6,1); 
  const timeToM=t=>{if(!t||!t.includes(':'))return 0;return t.split(':').reduce((a,b)=>a*60+Number(b),0);}; 
  const mToTime=m=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`; 
  const save=()=>localStorage.setItem('fb_calTasks',JSON.stringify(calTasks)); const saveProf=()=>localStorage.setItem('fb_profile',JSON.stringify(profile)); 
  const mNames=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"]; 
  const mTitle=$('#current-month-title'),pBtn=$('#prev-month-btn'),nBtn=$('#next-month-btn'),mPicker=$('#month-picker'),pGrid=$('#picker-grid'),pYear=$('#picker-year'); 
  const updateTitle=()=>{if(mTitle)mTitle.textContent=`${mNames[currentMonth.getMonth()]} ${currentMonth.getFullYear()}`;if(pBtn)pBtn.disabled=currentMonth<=minLim;if(nBtn)nBtn.disabled=currentMonth>=maxLim;}; 
  if(pBtn)pBtn.addEventListener('click',()=>{const p=new Date(currentMonth);p.setMonth(p.getMonth()-1);if(p>=minLim){currentMonth=p;renderCalendar();updateTitle();}}); 
  if(nBtn)nBtn.addEventListener('click',()=>{const n=new Date(currentMonth);n.setMonth(n.getMonth()+1);if(n<=maxLim){currentMonth=n;renderCalendar();updateTitle();}}); 
  if(mTitle&&mPicker){mTitle.addEventListener('click',()=>{renderPicker();mPicker.classList.add('open');});mPicker.addEventListener('click',e=>{if(e.target===mPicker)mPicker.classList.remove('open');});} 
  function renderPicker(){if(!pGrid||!pYear)return;const y=currentMonth.getFullYear();pYear.textContent=y;pGrid.innerHTML='';mNames.forEach((n,i)=>{const b=document.createElement('div');b.className='picker-month';b.textContent=n;const im=new Date(y,i,1);if(im<minLim||im>maxLim)b.classList.add('disabled');else{if(i===currentMonth.getMonth()&&y===currentMonth.getFullYear())b.classList.add('current');b.addEventListener('click',()=>{currentMonth=new Date(y,i,1);renderCalendar();updateTitle();mPicker.classList.remove('open');});}pGrid.appendChild(b);});} 
  function genTL(dateStr){const s=timeToM(profile.wake),e=timeToM(profile.sleep);if(!s||!e||s>=e)return[];const sch=[];let cur=s;const add=(t,ti,d,l=false)=>{const st=cur,en=st+d*60;sch.push({id:timelineCounter++,type:t,title:ti,start:st,end:en,duration:d,locked:l});cur=en;return cur;};if(timeToM(profile.meal1)>s)cur=timeToM(profile.meal1);add('meal','🍳 Завтрак',0.5,true);cur=timeToM(profile.meal1)+30;if(timeToM(profile.workS)>cur)cur=timeToM(profile.workS);add('blocked','🏢 Учёба/Работа',(timeToM(profile.workE)-timeToM(profile.workS))/60,true);cur=timeToM(profile.workE);if(cur<timeToM(profile.meal2))add('meal','🍽️ Обед',1,true);cur=Math.max(cur,timeToM(profile.meal2)+60);if(cur<timeToM(profile.meal3))add('meal','🍲 Ужин',1,true);cur=Math.max(cur,timeToM(profile.meal3)+60);const dt=calTasks.filter(t=>t&&t.date===dateStr&&t.hours>0);let fa=0;for(let task of dt){let h=task.hours;while(h>0&&cur<e){let step=Math.min(h,2);if(fa>=profile.breakEvery/60){add('break','☕ Перерыв',0.25,true);fa=0;}add('work',task.title,step);h-=step;fa+=step;}}add('sleep','😴 Сон',(1440-e)/60,true);return sch.filter(b=>b.duration>0&&b.end<=1440);} 
  const renderCalendar=()=>{const g=$('#calendar-grid');if(!g)return;g.innerHTML='';const y=currentMonth.getFullYear(),m=currentMonth.getMonth(),dInM=new Date(y,m+1,0).getDate();for(let d=1;d<=dInM;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const dT=calTasks.filter(t=>t&&t.date===ds);const tot=dT.reduce((s,t)=>s+(t.hours||0),0);const c=document.createElement('div');c.className=`day-cell ${ds===todayStr?'today':''}`;c.innerHTML=`<div class="day-num">${d}</div>${dT.slice(0,2).map(t=>`<div class="task-chip ${t.hours>2?'chip-high':t.hours>1?'chip-med':'chip-low'}">${t.title||'Блок'} (${t.hours||0}ч)</div>`).join('')}${dT.length>2?`<div style="font-size:0.65rem;color:var(--text-muted)">+${dT.length-2}</div>`:''}<div class="day-load">️ ${tot.toFixed(1)}ч</div>`;c.dataset.date=ds;g.appendChild(c);}}; 
  renderCalendar(); updateTitle(); 
  $('#calendar-grid').addEventListener('click',e=>{const c=e.target.closest('.day-cell');if(!c)return;selDate=c.dataset.date;timelineCounter=0;currentTimeline=genTL(selDate);renderTL();const pt=$('#panel-day-title');if(pt)pt.textContent=` ${new Date(selDate+'T00:00:00').toLocaleDateString('ru-RU')}`;if(area)area.classList.add('panel-open');}); 
  if($('#panel-close-btn')&&area)$('#panel-close-btn').addEventListener('click',()=>area.classList.remove('panel-open')); 
  function renderTL(){const tl=$('#day-timeline');if(!tl)return;tl.innerHTML='';currentTimeline.forEach(b=>{const d=document.createElement('div');d.className=`timeline-block t-${b.type}`;d.dataset.id=b.id;d.innerHTML=`<div class="block-time">${mToTime(b.start)}-${mToTime(b.end)}</div><div class="block-info"><div class="block-title">${b.title}</div><div class="block-meta">${b.duration.toFixed(1)} ч${b.locked?' (авто)':''}</div><div class="edit-controls"><input class="edit-input short" type="number" step="0.25" min="0" value="${b.duration}" data-field="duration" ${b.locked?'disabled':''}><input class="edit-input title" type="text" value="${b.title}" data-field="title" ${b.locked?'disabled':''}><button class="btn-xs lock ${b.locked?'':'unlocked'}" data-action="lock">${b.locked?'🔓':'🔒'}</button><button class="btn-xs del" data-action="del">🗑️</button></div></div>`;tl.appendChild(d);});updateSum();} 
  function updateSum(){const el=$('#day-summary');if(!el)return;const s=currentTimeline.reduce((a,b)=>a+b.duration,0);el.textContent=`Итого: ${s.toFixed(1)}ч / 24ч | Свободно: ${Math.max(0,24-s).toFixed(1)}ч`;el.className=`day-summary ${s>24?'warn':''}`;} 
  const dtl=$('#day-timeline');if(dtl){dtl.addEventListener('input',e=>{if(e.target.matches('.edit-input')){const id=parseInt(e.target.closest('.timeline-block').dataset.id);const b=currentTimeline.find(x=>x.id===id);if(b){if(e.target.dataset.field==='duration')b.duration=parseFloat(e.target.value)||0;if(e.target.dataset.field==='title')b.title=e.target.value;updateSum();}}});dtl.addEventListener('click',e=>{const btn=e.target.closest('.btn-xs');if(!btn)return;const id=parseInt(btn.closest('.timeline-block').dataset.id);const b=currentTimeline.find(x=>x.id===id);if(!b)return;if(btn.dataset.action==='lock'){b.locked=!b.locked;btn.textContent=b.locked?'':'🔓';btn.classList.toggle('unlocked',!b.locked);e.target.closest('.edit-controls').querySelectorAll('input').forEach(i=>i.toggleAttribute('disabled',b.locked));}if(btn.dataset.action==='del'){currentTimeline=currentTimeline.filter(x=>x.id!==id);renderTL();}});} 
  const abBtn=$('#add-block-btn');if(abBtn)abBtn.addEventListener('click',()=>{const ty=$('#new-type').value,ti=$('#new-title').value.trim()||'Новый блок',ho=parseFloat($('#new-hours').value)||1;const la=currentTimeline[currentTimeline.length-1]||{end:timeToM(profile.wake)*60};currentTimeline.push({id:timelineCounter++,type:ty,title:ti,start:la.end/60*60,end:la.end/60*60+ho*60,duration:ho,locked:false});renderTL();}); 
  const sdBtn=$('#save-day-btn');if(sdBtn)sdBtn.addEventListener('click',()=>{calTasks=calTasks.filter(t=>t.date!==selDate);currentTimeline.filter(b=>b.type==='work').forEach(b=>calTasks.push({id:`manual-${selDate}-${b.title}`,title:b.title,date:selDate,hours:b.duration}));save();renderCalendar();if(area)area.classList.remove('panel-open');}); 
  const rdBtn=$('#reset-day-btn');if(rdBtn)rdBtn.addEventListener('click',()=>{timelineCounter=0;currentTimeline=genTL(selDate);renderTL();}); 
  const opBtn=$('#open-profile-btn'),pm=$('#profile-modal');if(opBtn&&pm)opBtn.addEventListener('click',()=>{const sv=(id,v)=>{const e=$(`#${id}`);if(e)e.value=v;};sv('prof-sleep',profile.sleep);sv('prof-wake',profile.wake);sv('prof-work-s',profile.workS);sv('prof-work-e',profile.workE);sv('prof-meal1',profile.meal1);sv('prof-meal2',profile.meal2);sv('prof-meal3',profile.meal3);sv('prof-break',profile.breakEvery);sv('prof-max-focus',profile.maxFocus);pm.classList.add('open');}); 
  const pf=$('#profile-form');if(pf)pf.addEventListener('submit',e=>{e.preventDefault();const gv=(id,fb)=>{const el=$(`#${id}`);return el?el.value:fb;};profile.sleep=gv('prof-sleep',profile.sleep);profile.wake=gv('prof-wake',profile.wake);profile.workS=gv('prof-work-s',profile.workS);profile.workE=gv('prof-work-e',profile.workE);profile.meal1=gv('prof-meal1',profile.meal1);profile.meal2=gv('prof-meal2',profile.meal2);profile.meal3=gv('prof-meal3',profile.meal3);profile.breakEvery=parseInt(gv('prof-break',profile.breakEvery));profile.maxFocus=parseInt(gv('prof-max-focus',profile.maxFocus));saveProf();if(pm)pm.classList.remove('open');renderCalendar();}); 
  const mtBtn=$('#move-today-btn');if(mtBtn)mtBtn.addEventListener('click',()=>{const tm=new Date();tm.setDate(tm.getDate()+1);const ts=getLocalDateStr(tm);calTasks.forEach(t=>{if(t&&t.date===todayStr)t.date=ts;});save();renderCalendar();alert('✅ Перенесено на завтра.');}); 
  window.addEventListener('storage',e=>{if(e.key==='fb_calTasks'){calTasks=JSON.parse(e.newValue)||[];renderCalendar();}}); document.addEventListener('keydown',e=>{if(!$('#calendar-grid'))return;if(e.key==='ArrowRight'&&nBtn&&!nBtn.disabled)nBtn.click();if(e.key==='ArrowLeft'&&pBtn&&!pBtn.disabled)pBtn.click();if(e.key==='Escape'){if(area)area.classList.remove('panel-open');if(pm)pm.classList.remove('open');if(mPicker)mPicker.classList.remove('open');}if(e.key==='Enter'&&area&&area.classList.contains('panel-open'))sdBtn?.click();}); $$('.modal-close').forEach(b=>b.addEventListener('click',e=>{const o=e.target.closest('.modal-overlay');if(o)o.classList.remove('open');})); const isMob=window.matchMedia('(max-width:768px)').matches||'ontouchstart'in window; if(isMob){let sx=0;const g=$('#calendar-grid');if(g){g.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;},{passive:true});g.addEventListener('touchend',e=>{const df=e.changedTouches[0].clientX-sx;if(Math.abs(df)>50){if(df>0&&pBtn&&!pBtn.disabled)pBtn.click();else if(df<0&&nBtn&&!nBtn.disabled)nBtn.click();}},{passive:true});}} 
}

// === 5️⃣ СТАТИСТИКА ===
if ($('#heatmap-grid')) { const tasks=JSON.parse(localStorage.getItem('fb_tasks'))||[];const ct=tasks.filter(t=>t.col==='done'&&t.completedAt);const calcStreak=()=>{if(ct.length===0)return{current:0,max:0};const ud=[...new Set(ct.map(t=>t.completedAt))].sort().reverse();let cs=0,ms=0,ts=1;const td=new Date();td.setHours(0,0,0,0);const yd=new Date(td);yd.setDate(td.getDate()-1);const tds=getLocalDateStr(td),yds=getLocalDateStr(yd);if(ud.includes(tds)||ud.includes(yds)){let cd=ud.includes(tds)?tds:yds;let idx=ud.indexOf(cd);cs=1;while(idx<ud.length-1){const c=new Date(ud[idx]+'T00:00:00'),p=new Date(ud[idx+1]+'T00:00:00');if(Math.round((c-p)/86400000)===1){cs++;idx++;}else break;}}for(let i=0;i<ud.length-1;i++){const c=new Date(ud[i]+'T00:00:00'),p=new Date(ud[i+1]+'T00:00:00');if(Math.round((c-p)/86400000)===1)ts++;else{ms=Math.max(ms,ts);ts=1;}}ms=Math.max(ms,ts);return{current:cs,max:ms};};const sk=calcStreak();const th=ct.reduce((s,t)=>s+(t.totalH||0),0);$('#streak-value').textContent=sk.current;$('#max-streak-value').textContent=sk.max;$('#total-hours-value').textContent=th.toFixed(1)+'ч';const hg=$('#heatmap-grid'),hm=$('#heatmap-months');const tDate=new Date();const ds=91;let lm=-1;const dh={};ct.forEach(t=>{if(t.completedAt&&t.totalH)dh[t.completedAt]=(dh[t.completedAt]||0)+t.totalH;});for(let i=ds-1;i>=0;i--){const d=new Date(tDate);d.setDate(d.getDate()-i);const str=getLocalDateStr(d);const h=dh[str]||0;const b=document.createElement('div');b.className='heatmap-block';b.title=`${str}: ${h.toFixed(1)}ч`;if(h>0){if(h>=4)b.classList.add('level-4');else if(h>=2.5)b.classList.add('level-3');else if(h>=1)b.classList.add('level-2');else b.classList.add('level-1');}else b.classList.add('empty');hg.appendChild(b);if(d.getMonth()!==lm){const ml=document.createElement('div');ml.textContent=d.toLocaleDateString('ru-RU',{month:'short'});hm.appendChild(ml);lm=d.getMonth();}}const eb=$('#energy-bars');const ttc=ct.length||1;const cts={high:0,med:0,low:0};ct.forEach(t=>{if(t.energy)cts[t.energy]++;});const rBar=(l,c,cls)=>{const p=(c/ttc)*100;eb.innerHTML+=`<div class="energy-bar-row"><div class="energy-label">${l}</div><div class="energy-track"><div class="energy-fill ${cls}" style="width: ${p}%">${c>0?c+' задач':''}</div></div></div>`;};rBar('🔥 Высокая',cts.high,'fill-high');rBar('⚡ Средняя',cts.med,'fill-med');rBar('🔋 Низкая',cts.low,'fill-low'); }

// Export
const expBtn=$('#export-btn');if(expBtn){expBtn.addEventListener('click',()=>{const bk={app:"Ритм",version:"2.0",exportDate:new Date().toISOString(),tasks:JSON.parse(localStorage.getItem('fb_tasks'))||[],calendarTasks:JSON.parse(localStorage.getItem('fb_calTasks'))||[],profile:JSON.parse(localStorage.getItem('fb_profile'))||{}};const js=JSON.stringify(bk,null,2);const bl=new Blob([js],{type:"application/json"});const u=URL.createObjectURL(bl);const a=document.createElement('a');a.href=u;a.download=`ritm_backup_${getLocalDateStr(new Date())}.json`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);expBtn.textContent='✅';expBtn.style.background='var(--success)';setTimeout(()=>{expBtn.textContent='💾';expBtn.style.background='';},2000);});}
if(window.matchMedia('(max-width:768px)').matches||'ontouchstart'in window)$$('.card-3d').forEach(el=>el.style.transform='none');